config/routes.rb
Rails.application.routes.draw do
  
  root to: "students#index"
  
  devise_for :users
 
  resources :attendances

  resources :teachers

  resources :subjects

  resources :students do 
    member do
      get :mark_attendance_form
      post :mark_attendance
      get :show_all_attendance
    end
  end

  resources :standards

end

app/views/show/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :roll_number %><br>
    <%= f.number_field :roll_number %>
  </div>
  <div class="field">
    <%= f.label :standard_id %><br>
    <%= f.collection_select :standard_id, Standard.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/show/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/show/index.html.erb
<h1>Listing students</h1>
<% if current_user.is_teacher?%>
  <h1>Search Student</h1>
  <%= form_tag students_path, :method => 'get' do %>
    <p>
      <%= hidden_field_tag 'search_student' %>
      <%= text_field_tag :roll_number, params[:roll_number], placeholder: "Please Enter Roll Number", required: true %>
      <%=  select_tag "standard_id", options_from_collection_for_select(Standard.all, "id", "name"), prompt: "Please Select Standard", required: true %>
      <%= submit_tag "Search", :name => nil %>
      <%= link_to "<button>Clear Filter</button>".html_safe, students_path, :id=>"clear_filter", :class=>"clear_filter" %>
    </p>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Roll number</th>
      <th>Standard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% unless @students.blank?%>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.roll_number %></td>
        <td><%= student.standard.try(:name) %></td>
        <% if current_user.is_teacher? %>
          <td><%= link_to 'Mark Attendance', mark_attendance_form_student_path(student) %></td>
          <% end %>
          <% if current_user.is_student? %>
           <td><%= link_to 'Show Attendance', show_all_attendance_student_path(student) %></td>
        <% end %>
        <td><%= link_to 'Show', student %></td>
         <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    
    <% end %>
    <%end%>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/show/mark_attendance_form.html.erb
<h1>Mark Attendance</h1>
<%= form_tag mark_attendance_student_path(@student), :method => 'post' do %>
  <%= date_field_tag(:attendance_date, Date.today) %>

  <ul>
    <% @subjects.each do |subject| %>
        <li>
          <%= check_box_tag 'subject_ids[]', subject.id -%>
          <%= h subject.name -%>
        </li>
    <% end %>
  </ul>


  <br/ >
  <br/ >
  <br/ >
  <%= submit_tag "Submit Attendance", :name => nil %>
<% end %>

app/views/show/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/show/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Roll number:</strong>
  <%= @student.roll_number %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @student.standard.try(:name) %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>